name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: php:8.2-fpm

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          apt-get update -yqq
          apt-get install -yqq git zip unzip libzip-dev libpng-dev libonig-dev libxml2-dev curl libcurl4-openssl-dev

      - name: Install PHP extensions
        run: |
          docker-php-ext-install pdo_mysql mbstring zip gd intl opcache curl xml

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          composer install --no-interaction
          npm install

      - name: Prepare environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run tests
        run: php artisan test

  registry_publish:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read 
      packages: write
    env:
      DOCKER_USERNAME: corin-alt 
      IMAGE_NAME: laravel-cicd-github
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${DOCKER_USERNAME}/${IMAGE_NAME}:latest .
          docker push ghcr.io/${DOCKER_USERNAME}/${IMAGE_NAME}:latest